# Numpy Assignment - Sriram Venkatesh


## 1. Create a null vector of size 10 but the fifth value which is 1.

In [8]:
import numpy as np

In [9]:
a = np.zeros(10)
a[4]=1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


## 2. Create a vector with values ranging from 10 to 49.


In [10]:
b = np.arange(10,50)
print(b)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


## 3. Create a 3x3 matrix with values ranging from 0 to 8

In [11]:
c = np.arange(9).reshape(3,3)
print(c)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 4. Find indices of non-zero elements from [1,2,0,0,4,0]

In [12]:
d = np.nonzero([1,2,0,0,4,0])
print(d)

(array([0, 1, 4], dtype=int64),)


## 5. Create a 10x10 array with random values and find the minimum and maximum values.

In [13]:
e = np.random.random((10,10))
emax, emin = e.max(), e.min()
print(emax, emin)

0.9878587593308359 0.003665291904135559


## 6. Create a random vector of size 30 and find the mean value.


In [14]:
f = np.random.random(30)
g = f.mean()
print(g)

0.4881226285699463
